# Generated by Django 4.2.1 on 2023-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_ordererd_remove_cart_ordererd_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordererd',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordererd_date',
            new_name='ordered_date',
        ),
    ]
